### ISSUE TITLE
[功能建议]与HGFaceDD连接时，可考虑使用Bonjour作服务发现

### ISSUE THREAD

**Issue by CmST0us** [TachibanaSuzume/FaceXD#2]
使用Bonjour作服务发现时，可以自动获取目标服务IP与端口，提高配对体验
需要HGFaceDD配合引入Bonjour

**Comment by TachibanaSuzume** [comment]
目前正在对接prprlive和aien，需要和他们沟通一下出sdk给他们对接

**Comment by CmST0us** [comment]
可以，如果和其他直播App对接的话，最好先确定协议。bonjour只是作为一个服务发现，方便连接的组件。具体通信还是需要双方确定。

**Comment by CmST0us** [comment]
已加入USB NoDo
