### ISSUE TITLE
[功能建议]加入开关的悬浮功能解释或直接URL跳转至用户指南

### ISSUE THREAD

**Issue by ShigemoriHakura** [TachibanaSuzume/FaceXD#20]
有些功能的意思单靠开关的文字无法解释清楚
比如启用socket，不开启实际上是走HTTP Post，但是目前的文本无法让用户明白这个开关的意义

**Comment by CmST0us** [comment]
话说HTTP有客户在用吗？

**Comment by ShigemoriHakura** [comment]
（好像还没有呢（

**Comment by CmST0us** [comment]
我觉得是不是可以砍了？维护两个方式成本挺高的

**Comment by ShigemoriHakura** [comment]
砍了倒是没问题，这个功能建议主要是之前际爸过来问“相机坐标系”是什么所以想起来要做一下

**Comment by CmST0us** [comment]
不使用相机坐标的时候，相当于人脸处于世界坐标的绝对位置上。移动旋转手机不会影响捕捉
使用相机坐标的时候，移动相机会影响人脸捕捉
