### ISSUE TITLE
[参数传递]bodyAngle参数不应由APP计算传递

### ISSUE THREAD

**Issue by CmST0us** [TachibanaSuzume/FaceXD#3]
bodyAngleX
bodyAngleY
bodyAngleZ
三个参数依赖于head姿态数据，不能直接由硬件获取。故在传递json时建议不要加到里面，而是由HGFaceDD 完成计算。
其他需要计算的参数同理。在发送时尽量保证发送原始数据。

如果要需求是要做到手机上的显示界面和HGFaceDD一样，可以忽略此问题

**Comment by TachibanaSuzume** [comment]
目前是要做到一样的显示
用户如果有自己操作和调整的需求的话直接开启原始数据选项即可
这个就先close了
