### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Moe-MCU** [TachibanaSuzume/FaceXD#43]
萌新求教（
Showing All Messages
/Users/***/Documents/Files/git/FaceXD/Pods/Target Support Files/Pods-FaceXD/Pods-FaceXD.debug.xcconfig: unable to open file (in target "FaceXD" in project "FaceXD")

Showing All Messages
Unable to load contents of file list: '/Target Support Files/Pods-FaceXD/Pods-FaceXD-frameworks-Debug-output-files.xcfilelist'

**Comment by CmST0us** [comment]
运行了pod update了吗？

**Comment by Moe-MCU** [comment]
收到～问题已解决
