### ISSUE TITLE
Build?

### ISSUE THREAD

**Issue by timwillhack** [TachibanaSuzume/FaceXD#58]
I don't have a mac but wanted to use this on my phone to use as a camera in an app on my desktop (which says it supports Face XD) is there anyway to build it so it can be sent to an iphone or publish it to the app store?  Is it maybe in the Japanese app store under a different name or something?  Thanks

**Comment by CmST0us** [comment]
FaceXD has renamed to AMGFace, youcan download AMGFace at this link
https://apps.apple.com/jp/app/amgface/id1511883380
Thanks
